openapi: 3.0.0
info:
  title: Product API
  description: API for managing products, including creation, listing, and retrieval.
  version: 1.0.0
servers:
  - url: http://localhost:9292
    description: Local server

paths:
  /auth:
    post:
      summary: Authenticate user and generate JWT token
      operationId: authenticateUser
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: The JWT token
                  message:
                    type: string
                    description: Authentication message
        '401':
          description: Unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message for unauthorized access

  /products:
    get:
      summary: Retrieve a list of products
      operationId: listProducts
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: The product's unique ID
                    name:
                      type: string
                      description: The product's name
    post:
      summary: Create a new product
      operationId: createProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the product to be created
      responses:
        '202':
          description: Product creation in progress
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Message indicating the product creation is in progress

  /products/{id}:
    get:
      summary: Retrieve a specific product by ID
      operationId: getProduct
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The product's unique ID
      responses:
        '200':
          description: The requested product
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The product's unique ID
                  name:
                    type: string
                    description: The product's name
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message indicating the product was not found

  /openapi.yaml:
    get:
      summary: Retrieve the OpenAPI specification
      operationId: getOpenApiSpec
      responses:
        '200':
          description: The OpenAPI specification file
          content:
            application/yaml:
              schema:
                type: string
                format: uri
                description: The OpenAPI specification file

  /AUTHORS:
    get:
      summary: Retrieve the AUTHORS file
      operationId: getAuthorsFile
      responses:
        '200':
          description: The AUTHORS file
          content:
            text/plain:
              schema:
                type: string
                description: The AUTHORS file content

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
